apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
stringData:
  slack-url: "https://hooks.slack.com/services/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"
