apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: kps   
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestAlert
      expr: vector(1)
      for: 5s
      labels:
        severity: warning
      annotations:
        summary: "Test alert firing"
        description: "This is a test alert firing to Slack"
