apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: example
    rules:
    - alert: HighCPUExample
      expr: sum(rate(container_cpu_usage_seconds_total{container!="", namespace=~"monitoring"}[2m])) > 0.01
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Example CPU alert to test Slack notifications"
