apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitoring
  labels:
    role: alert-rules
spec:
  groups:
  - name: test-alerts
    rules:
    - alert: TestAlertFiring
      expr: vector(1)
      for: 0m
      labels:
        severity: warning
        namespace: test-namespace
      annotations:
        summary: "This is a test firing alert"
        description: "The TestAlertFiring alert is triggered to validate Slack integration"
